source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LEOTab_Example', :exclusive => true do
  pod "LEOTab", :path => "../"
end

target 'LEOTab_Tests', :exclusive => true do
  pod "LEOTab", :path => "../"

  
end
